services:
  app:
    build: .
    ports:
      - "3001:3001"
    env_file: .env
    volumes:
      - .:/app          # syncs host folder with container — files written inside now persist
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orbitalops
    volumes:
      - pgdata:/var/lib/postgresql/data
    # No ports needed.
    # The app reaches PostgreSQL over Docker's internal network
    # using hostname "postgres".

  redis:
    image: redis:7
    # No ports needed.
    # The app reaches Redis over Docker's internal network
    # using hostname "redis".

  worker:
    build: .
    command: node src/workers/telemetryWorker.js
    env_file: .env
    volumes:
      - .:/app          # syncs host folder with container — files written inside now persist
      - /app/node_modules
    depends_on:
      - postgres
      - redis

volumes:
  pgdata: